### ISSUE TITLE
information when machinekit fails is wrong/inadequate

### ISSUE THREAD

**Issue by ArcEye** [machinekit/machinekit-cnc#44]
<a href="https://github.com/luminize"><img src="https://avatars1.githubusercontent.com/u/2206842?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [luminize](https://github.com/luminize)**
_Wed Apr  4 06:53:44 2018_
_Originally opened as https://github.com/machinekit/machinekit/issues/1366_

----

When something fails the following is shown:

```
See /var/log/linuxcnc.log for more information.
Shutting down and cleaning up Machinekit...
Cleanup done
Machinekit terminated with an error.  You can find more information in the log:
   /home/machinekit/linuxcnc_debug.txt
and
   /home/machinekit/linuxcnc_print.txt
as well as in the output of the shell command 'dmesg' and in the terminal
```

Personally I think this is wrong info and should contain better instructions, like something as "start with export DEBUG=5" and "look at /var/log/linuxcnc.log before posting". Maybe some basic instructions in helping people narrowing down.

I don't remember ever finding anything in linuxcnc_debux.txt or linuxcnc_print.txt

Opinions?

**Comment by ArcEye** [comment]
<a href="https://github.com/ArcEye"><img src="https://avatars2.githubusercontent.com/u/770392?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ArcEye](https://github.com/ArcEye)**
_Wed Apr  4 08:41:19 2018_

----

> I don't remember ever finding anything in linuxcnc_debux.txt or linuxcnc_print.txt

It only shows something useful if it it pretty basic.

Quite simple to add something here
https://github.com/machinekit/machinekit/blob/master/scripts/linuxcnc.in#L210

May need to specifically mentions insmod.
Say something to the effect that 
"It indicates a component / modules did not load.
To find the reason for it you need to `export DEBUG=5` and run again with exactly the same config.
Then linuxcnc.log and dmesg should between them have sufficient information to enable diagnosis.
The insmod error code on its own is often quite imprecise and cannot be solely relied upon"

**Comment by luminize** [comment]
I'll take on this one, seems pretty easy and doable in some in-between time

**Comment by luminize** [comment]
Do we need to look at machinekit-hal too?

**Comment by luminize** [comment]
(sorry, forget my last remark... just noted the cross-stack issue label)
