### ISSUE TITLE
halshow not working - how long has it been broken?

### ISSUE THREAD

**Issue by ArcEye** [machinekit/machinekit-cnc#70]
Whilst testing the combined `machinekit-hal` & `machinekit-cnc` I found that the 'Machine Configuration' menu item in Axis did not work because tcl/hal.so was missing.

Added code to build it, but it is not right yet (another issue).

However when testing machinekit, under Buster, Stretch and Jessie, I found that 'Machine Configuration' does not work there either.
It throws an error thus
```
Error in startup script: couldn't load file "/usr/lib/tcltk/linuxcnc/hal.so":
 /usr/lib/tcltk/linuxcnc/hal.so: undefined symbol: tclStubsPtr
    while executing
"load $::linuxcnc::TCL_LIB_DIR/hal.so"
    (procedure "hal" line 2)
    invoked from within
"hal list $node"
    (procedure "listHAL" line 5)
    invoked from within
"listHAL"
    (procedure "refreshHAL" line 12)
    invoked from within
"refreshHAL"
    (file "/usr/lib/tcltk/linuxcnc/bin/halshow.tcl" line 578)
```

It is not something I have used for ages, as I have a Qt program which does a better job (IMHO)

Does anyone know when this died?

**Comment by ArcEye** [comment]
Well what do know, this may have been broken for several years. :laughing: 

The root of the problem is that tclStubsPtr was removed from the tcl8.x-dev package 4 years ago!!!
https://alioth-lists.debian.net/pipermail/pkg-tcltk-devel/2014-October/002697.html

I have now got it working by adding `libtclstub.a` to the Submakefile which creates `hal.so`

So package `tcl-dev` needs adding to the build deps for `machinekit` and `machinekit-cnc` and the Submakefile change needs committing to both.

Just when I was trying to deal with one problem, I find another to fix.
Ho Hum

**Comment by zultron** [comment]
I'll fix up the Docker images.  Thanks for figuring this out!

**Comment by ArcEye** [comment]
@zultron you are a star
I will fix my buster dockers too, but not today:)

**Comment by ArcEye** [comment]
My dockers are done and I have made test builds.

@zultron let me know when yours are ready for a pull and I will test all of them

**Comment by zultron** [comment]
@ArcEye Sorry, while adding `tcl-dev` I'm also stuffing a few other changes into the images that have been hanging out in my tree for a while.  They're working now, but need a little more testing and a final build.  I'll have them done by tomorrow.

New changes are:
- Add `tcl-dev` package, of course
- Support Buster
- Support of new-style Docker Hub automated builds
- Other misc tweaks

**Comment by ArcEye** [comment]
That's fine, I am busy doing something else now anyway.
I will check again tomorrow

**Comment by zultron** [comment]
(As noted in other channels) Docker images are ready for testing at https://hub.docker.com/r/zultron/mk-cross-builder/ ; once they're shown to work, I'll promote them to the main https://hub.docker.com/r/dovetailautomata/mk-cross-builder/ repository.

**Comment by ArcEye** [comment]
I take it you now need to get the yapps installs right for the dockers, so I will leave it a bit longer.

Didn't realise you had used your other docker repo, have been trying the main one with no update seen :laughing:

**Comment by zultron** [comment]
Yes, Docker images are ready for testing at https://hub.docker.com/r/zultron/mk-cross-builder/ , please give them a try.  They have the yapps packages all ready to go; see the build of PR machinekit/machinekit-hal#194 in Travis CI [here][1], passing.

Once these images get your blessing, I'll promote them to the dovetailautomata/mk-cross-builder Docker Hub repo and they'll be official.

[1]:  https://travis-ci.org/zultron/machinekit-hal/builds/505693192

**Comment by ArcEye** [comment]
OK, I have a test script running to build all arch and all distros, see how it goes

**Comment by ArcEye** [comment]
@zultron 
My script just built machinekit, for simplicity, with all the dockers for each distro
There is one error in 2 builds.

In an armhf_10 build and an i386_10 build, this occurs
```
dh_compress -X.pdf -X.txt -X.hal -X.ini -X.clp -X.var -X.nml \
    -X.tbl -X.xml -Xsample-configs
dh_fixperms -X/linuxcnc_module_helper -X/rtapi_app_
dh_python2 --ignore-shebangs --no-guessing-versions --no-ext-rename
W: dh_python2:479: Please add dh-python package to Build-Depends
Usage: dh_python2 -p PACKAGE [-V [X.Y][-][A.B]] DIR [-X REGEXPR]

dh_python2: error: no such option: --no-ext-rename
make: *** [debian/rules:230: binary-arch] Error 2
dpkg-buildpackage: error: debian/rules binary-arch subprocess returned exit status 2
```
amd64_10 builds fine.

So looks like missing `dh_python2`, other than that it should be OK

When you have updated I will run the full script, to build all repos, in all architectures and distros just to be sure

**Comment by zultron** [comment]
Did you see commit [25cf1da7][1] over in `machinekit-hal`?  That wouldn't have made it into the legacy `machinekit` repo.

[1]: https://github.com/machinekit/machinekit-hal/commit/25cf1da7

**Comment by zultron** [comment]
Oh, while that commit does fix the problem, your comment got me to re-read the error message so I now understand why the `amd64_10` succeeds.  I'll add the `dh-python` package in the base filesystem on cross-build Dockers with `/sysroot`.

More generally, in the future I'll remember to look at this kind of problem when failures only occur in cross-builds.

**Comment by zultron** [comment]
The `amd64_8` and `amd64_10` images are still building; should be done in 30-60 minutes.

Those happen to be the native build containers which don't have the problem, though, so your scripts should actually succeed right now.

**Comment by ArcEye** [comment]
OK, I am running out of time this morning.
Will just re-run the last test script before I leave and look at the other repos later.

**Comment by ArcEye** [comment]
@zultron 
Tested all dockers, building all distros / all repos
All pass.

**Comment by zultron** [comment]
Yay!  I'll take that as a blessing to promote the Docker image updates to the [production repo][1] on Docker Hub.

[1]: https://hub.docker.com/r/dovetailautomata/mk-cross-builder/

**Comment by ArcEye** [comment]
If they don't fail in local invocations, can't see any reason why they should on the server.
However I will run a build for each of the repos later, so that the new docker is already pulled to cut down delays later.

**Comment by ArcEye** [comment]
The issue which started this,  is now fixed by https://github.com/machinekit/machinekit-hal/pull/197
Tested and halshow now works when `machinekit-hal` and `machinekit-cnc` packages are combined
