### ISSUE TITLE
scripts/{get-git-sha,check-build-vs-configure-sha} missing

### ISSUE THREAD

**Issue by mbuesch** [machinekit/machinekit-cnc#78]
The build complains:

```
make[1]: ../scripts/get-git-sha: Command not found
make[1]: ../scripts/check-build-vs-configure-sha: Command not found
```

Should these scripts be copied over from machinekit-hal?

**Comment by ArcEye** [comment]
I will have to look at whether it does anything useful and is needed at all.
Packages and RIPs build quite happily without it.

Probably removed from -cnc because generally files can only be in -hal or -cnc, not both.
Could be re-introduced so long as it is hidden from the packaging installs.
